# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-01 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hemocentros_hemocentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_hemocentro', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
