# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-01 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hemocentros_hemocentro',
            new_name='hemocentro',
        ),
    ]
