# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hemocentros', '0002_auto_20180901_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hemocentro',
        ),
    ]
