# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hemocentros', '0003_delete_hemocentro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_hemocentro', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
