# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-25 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending payment'), (1, 'Concluded'), (2, 'Canceled')], default=0, verbose_name='Situação')),
                ('payment_option', models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal')], default='paypal', max_length=20, verbose_name='Opção de Pagamento')),
                ('order_key', models.CharField(db_index=True, max_length=40, verbose_name='Chave da compra')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor do Pedido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('open', models.BooleanField(default=False)),
                ('group', models.ManyToManyField(to='auth.Group')),
                ('keywords', models.ManyToManyField(blank=True, to='avec.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(default=0, verbose_name='Cód. do país')),
                ('country_name', models.CharField(max_length=150, verbose_name='Nome do país')),
                ('country_slug', models.CharField(max_length=160, verbose_name='Abreviação')),
                ('pvalue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor do Plano')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de modificação')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_price', to='auth.Group', verbose_name='Plano de assinatura')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços dos Planos',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pdf', models.FileField(upload_to='pdf')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='avec.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='avec.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='avec.Keywords')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.Themes'),
        ),
        migrations.AddField(
            model_name='reports',
            name='subject',
            field=models.ManyToManyField(related_name='subparent1', to='avec.Subject'),
        ),
        migrations.AddField(
            model_name='reports',
            name='subject_detail',
            field=models.ManyToManyField(related_name='subchild1', to='avec.Subject_detail'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ManyToManyField(related_name='subparent', to='avec.Subject'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject_detail',
            field=models.ManyToManyField(related_name='subchild', to='avec.Subject_detail'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='avec.Price', verbose_name='Plano de assinatura'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
