# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('avec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('open', models.BooleanField()),
                ('group', models.ManyToManyField(to='auth.Group')),
                ('keywords', models.ManyToManyField(blank=True, related_name='keywords_dash', to='avec.Keywords')),
                ('subject', models.ManyToManyField(related_name='subparent_dash', to='avec.Subject')),
                ('subject_detail', models.ManyToManyField(related_name='subchild_dash', to='avec.Subject_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Dashsource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.CharField(max_length=200)),
                ('extract_date', models.DateTimeField(blank=True, null=True)),
                ('dash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.Dashboard')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='open',
            field=models.BooleanField(),
        ),
    ]
