# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-09 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0002_auto_20170409_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Pedido'),
        ),
    ]
