# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0003_auto_20170409_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Plano'),
        ),
    ]
