# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0005_auto_20170427_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('script', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('search_field', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='View_Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='View_Subject_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.View_Subject')),
            ],
        ),
        migrations.CreateModel(
            name='View_Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.View_Client')),
            ],
        ),
        migrations.AddField(
            model_name='paineis',
            name='text',
            field=models.TextField(default='adicione um texto descritivo aqui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simpledashboard',
            name='text',
            field=models.TextField(default='adicione um texto descritivo aqui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='categorizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='elaboracao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='fonte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='indicador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='metodo_calculo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='origem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='periodicidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='periodos_disponiveis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabsimple',
            name='titulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='view_subject',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avec.View_Themes'),
        ),
    ]
