# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-01 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0006_auto_20170619_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='categorizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='elaboracao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='fonte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='indicador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='metodo_calculo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='origem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='periodicidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='periodos_disponiveis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='titulo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='view_client',
            name='open',
            field=models.BooleanField(default=datetime.datetime(2017, 7, 1, 9, 26, 34, 731764)),
            preserve_default=False,
        ),
    ]
