# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0014_view_client_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabpaineis',
            name='categorizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='elaboracao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='fonte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='indicador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='metodo_calculo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='origem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='periodicidade',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='periodos_disponiveis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tabpaineis',
            name='titulo',
            field=models.TextField(blank=True),
        ),
    ]
