# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0015_auto_20170626_1829'),
        ('avec', '0007_auto_20170701_0926'),
    ]

    operations = [
    ]
