# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-09 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0021_remove_post_link'),
        ('avec', '0002_auto_20170219_1736'),
    ]

    operations = [
    ]
