# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-15 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0022_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reports',
            name='pdf',
            field=models.FileField(upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='themes',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
