# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0022_remove_view_client_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_client',
            name='image2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
