# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-22 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('avec', '0023_auto_20170315_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='post',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
