# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avec', '0025_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending payment'), (1, 'Concluded'), (2, 'Canceled')], default=0, verbose_name='Situação')),
                ('payment_option', models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal')], default='paypal', max_length=20, verbose_name='Opção de Pagamento')),
                ('order_key', models.CharField(db_index=True, max_length=40, verbose_name='Chave do Plano')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auth.Group', verbose_name='Plano de assinatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços dos Planos'},
        ),
        migrations.AlterField(
            model_name='price',
            name='country_code',
            field=models.IntegerField(default=0, verbose_name='Cód. do país'),
        ),
        migrations.AlterField(
            model_name='price',
            name='country_name',
            field=models.CharField(max_length=150, verbose_name='Nome do país'),
        ),
        migrations.AlterField(
            model_name='price',
            name='country_slug',
            field=models.CharField(max_length=160, verbose_name='Abreviação'),
        ),
        migrations.AlterField(
            model_name='price',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='price',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_price', to='auth.Group', verbose_name='Plano de assinatura'),
        ),
        migrations.AlterField(
            model_name='price',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de modificação'),
        ),
        migrations.AlterField(
            model_name='price',
            name='pvalue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor do Plano'),
        ),
    ]
