# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0026_auto_20170323_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='group',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='avec.Price', verbose_name='Plano de assinatura'),
        ),
    ]
