# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avec', '0028_auto_20170323_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending payment'), (1, 'Concluded'), (2, 'Canceled')], default=0, verbose_name='Situação')),
                ('payment_option', models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'Paypal')], default='paypal', max_length=20, verbose_name='Opção de Pagamento')),
                ('order_key', models.CharField(db_index=True, max_length=40, verbose_name='Chave do Plano')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('price', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='avec.Price', verbose_name='Plano de assinatura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
    ]
