# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0029_view_client_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_client',
            name='script',
            field=models.CharField(blank=True, max_length=201),
        ),
    ]
