# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0032_view_client_no_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgf_municipio_gis',
            fields=[
                ('cd_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_municipio', models.CharField(max_length=250, null=True)),
                ('codigo_uf', models.CharField(max_length=30, null=True)),
                ('uf', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='view_client',
            name='subtitle',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='view_client',
            name='script',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
