# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-11-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0033_auto_20171130_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgf_municipio',
            name='populacao_estimada',
            field=models.IntegerField(null=True),
        ),
    ]
