# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-02 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0035_auto_20171130_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgf_acao_detalhe',
            name='cd_acao',
        ),
        migrations.DeleteModel(
            name='pgf_acao_detalhe',
        ),
    ]
