# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0036_auto_20171202_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgf_acao_detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.CharField(max_length=200, null=True)),
                ('n_ob', models.CharField(max_length=200, null=True)),
                ('dt_ob', models.CharField(max_length=200, null=True)),
                ('tp_repasse', models.CharField(max_length=30, null=True)),
                ('banco_ob', models.CharField(max_length=30, null=True)),
                ('agencia_ob', models.CharField(max_length=30, null=True)),
                ('conta_ob', models.CharField(max_length=30, null=True)),
                ('vl_total', models.CharField(max_length=30, null=True)),
                ('vl_desconto', models.CharField(max_length=30, null=True)),
                ('vl_liquido', models.CharField(max_length=30, null=True)),
                ('mt_rejeicao', models.CharField(max_length=30, null=True)),
                ('nr_processo', models.CharField(max_length=30, null=True)),
                ('nr_proposta', models.CharField(max_length=30, null=True)),
                ('nr_portaria', models.CharField(max_length=30, null=True)),
                ('acao_num', models.CharField(max_length=30, null=True)),
                ('cd_acao_str', models.CharField(max_length=30, null=True)),
                ('cd_acao', models.ForeignKey(db_column='cd_acao', on_delete=django.db.models.deletion.CASCADE, to='avec.pgf_acao')),
            ],
        ),
    ]
