# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0048_auto_20171203_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_entidade',
            name='nm_prefeito',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pgf_entidade',
            name='nm_secretario',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
