# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0049_auto_20171204_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_detalhe',
            name='cnpj',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
