# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0050_pgf_acao_detalhe_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_detalhe',
            name='dt_ob_date',
            field=models.DateTimeField(null=True),
        ),
    ]
