# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0051_pgf_acao_detalhe_dt_ob_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgf_acao_datasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_municipio', models.CharField(max_length=200, null=True)),
                ('mes', models.CharField(max_length=20, null=True)),
                ('desc_subgrupo', models.CharField(max_length=200, null=True)),
                ('grupo', models.CharField(max_length=200, null=True)),
                ('total', models.CharField(max_length=200, null=True)),
                ('municipal_plena', models.CharField(max_length=200, null=True)),
                ('estadual_plena', models.DateTimeField(null=True)),
                ('subgrupo', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
