# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0052_pgf_acao_datasus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgf_acao_datasus',
            name='estadual_plena',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
