# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0053_auto_20171206_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='desc_subgrupo',
        ),
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='estadual_plena',
        ),
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='municipal_plena',
        ),
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='subgrupo',
        ),
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='total',
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='sum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
