# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0054_auto_20171206_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgf_acao_datasus_grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_municipio', models.CharField(max_length=200, null=True)),
                ('mes', models.CharField(max_length=20, null=True)),
                ('grupo', models.CharField(max_length=200, null=True)),
                ('sum', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pgf_acao_datasus',
            name='sum',
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='desc_subgrupo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='estadual_plena',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='municipal_plena',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='subgrupo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='total',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
