# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0058_auto_20171206_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
