# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0059_pgf_acao_datasus_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='amb_hosp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='pacto_gestao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
