# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0060_auto_20171210_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgf_acao_datasus',
            name='pacto_gestao',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
