# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0061_auto_20171210_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_faec',
            name='cd_municipio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
