# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0062_pgf_acao_faec_cd_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgf_acao_faec',
            name='cd_municipio',
        ),
        migrations.AddField(
            model_name='pgf_acao',
            name='cd_municipio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
