# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avec', '0063_auto_20171214_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgf_acao_datasus',
            name='ano',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
