# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='imgprofile',
            field=models.TextField(default='', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_from_socialnetwork',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
