# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170417_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_from_socialnetwork',
            field=models.BooleanField(default=False, verbose_name='Login Social'),
        ),
    ]
