# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-21 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170315_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=22, null=True, verbose_name='Telefone'),
        ),
    ]
