# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170321_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Um nome curto que sera usado para identifica-lo de forma unica na plataforma', max_length=30, unique=True, verbose_name='Usuário'),
        ),
    ]
